name: Lint
permissions:
  contents: read
  pull-requests: write

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
      - uses: psf/black@0eddb3d6412608832c82668c8629d8b65676099a
        with:
          options: "--check --verbose"
          version: "~= 25.1"
          