name: Lint
permissions:
  contents: read
  pull-requests: write

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
      - uses: psf/black@262ad62ca9f1d1b1537cc95a91643fb781d7c501
        with:
          options: "--check --verbose"
          version: "~= 25.1"
          